project:
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "!*.ipynb"

website:
  title: "Orenaikeblog"
  site-url: https://oredesigns.blog
  description: "Here and now — by O.Orenaike"
  navbar:
    right:
      - about.qmd
      - portfolio.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/Otomisin
      - icon: twitter
        href: https://twitter.com/orenaiket
      - icon: linkedin
        href: https://www.linkedin.com/in/tosin-orenaike
  page-footer: 
    left: "Copyright 2021, O.Orenaike" 
    right: 
      - icon: github
        href: https://github.com/Otomisin
      - icon: twitter 
        href: https://twitter.com/orenaiket
      - icon: linkedin
        href: https://www.linkedin.com/in/tosin-orenaike
toc: true
format:
  html:
    theme:
      - cosmo
      - custom.scss

resources:
  - CNAME

